openapi: "3.1.0"
info:
  title: "fellows-project761-team10"
  version: "1.0.0"
  description: "fellows-project761-team10-API-for-user-profile-management"
servers:
  - url: "__SWAGGER_API_BASE_URL__"
paths:
  /api/auth/verify/{id}:
    post:
      tags:
        - Auth Controller
      summary: Verify user profile by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: User profile ID
      responses:
        '200':
          description: Profile verified
        '404':
          description: Profile not found
        '500':
          description: Internal server error

  /api/auth/updatePassword/{id}:
    put:
      tags:
        - Auth Controller
      summary: update password
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: User profile ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Password updated successfully
        '404':
          description: Password not found
        '500':
          description: Internal server error

  /api/auth/verify/{isVerified}:
    get:
      tags:
        - Auth Controller
      summary: get business user profiles for verification 
      parameters:
        - name: isVerified
          in: path
          required: true
          schema:
            type: boolean
          description: Profile verification status
      responses:
        '200':
          description: Profiles found
        '404':
          description: Profiles not found
        '500':
          description: Internal server error

  /api/auth/account-screen:
    post:
      tags:
        - Auth Controller
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                organization_name:
                  type: string
      responses:
        '200':
          description: Account info create successfully
        '500':
          description: Internal server error

  /api/userprofile:
   get:
      tags:
        - User Profile Controller
      summary: Get all user profiles
      responses:
        '200':
          description: User profiles found
        '404':
          description: No user profiles found
        '500':
          description: Internal server error
   post:
      tags:
        - User Profile Controller
      summary: Create a new user profile
      description: This endpoint creates a new user profile with the given details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usertypeid:
                  type: integer
                institution_id:
                  type: integer
                faculty_id:
                  type: integer
                organization_id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                preferred_name:
                  type: string
                title:
                  type: string
                primary_email:
                  type: string
                  format: email
                department:
                  type: string
                orcid_identifier:
                  type: string
                linkedin_url:
                  type: string
                secondary_email:
                  type: string
                mobile_phone:
                  type: string
                bio:
                  type: string
                research_area:
                  type: string
                skills:
                  type: string
                research_tags:
                  type: string
                expertise:
                  type: string
                positions:
                  type: string
                tools:
                  type: string
                profile_picture:
                  type: string
                is_verified:
                  type: boolean
                signup_datetime:
                  type: string
                  format: date-time
      responses:
        '201':
          description: User profile created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
   put:
      tags:
      summary: update a user profile with id in the request body
      description: update user profile, put the profile id in the request body
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                usertypeid:
                  type: integer
                institution_id:
                  type: integer
                faculty_id:
                  type: integer
                organization_id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                preferred_name:
                  type: string
                title:
                  type: string
                primary_email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                department:
                  type: string
                orcid_identifier:
                  type: string
                linkedin_url:
                  type: string
                secondary_email:
                  type: string
                mobile_phone:
                  type: string
                bio:
                  type: string
                research_area:
                  type: string
                skills:
                  type: string
                research_tags:
                  type: string
                expertise:
                  type: string
                positions:
                  type: string
                tools:
                  type: string
                profile_picture:
                  type: string
                is_verified:
                  type: boolean
                signup_datetime:
                  type: string
                  format: date-time
      responses:
        '200':
          description: User profile updated successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/userprofile/{id}:
    put:
      tags:
        - User Profile Controller
      summary: Update user profile by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: User profile ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usertypeid:
                  type: integer
                institution_id:
                  type: integer
                faculty_id:
                  type: integer
                organization_id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                preferred_name:
                  type: string
                title:
                  type: string
                primary_email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                department:
                  type: string
                orcid_identifier:
                  type: string
                linkedin_url:
                  type: string
                secondary_email:
                  type: string
                mobile_phone:
                  type: string
                bio:
                  type: string
                research_area:
                  type: string
                skills:
                  type: string
                research_tags:
                  type: string
                expertise:
                  type: string
                positions:
                  type: string
                tools:
                  type: string
                profile_picture:
                  type: string
                is_verified:
                  type: boolean
                signup_datetime:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Profile updated
        '404':
          description: Profile not found
        '500':
          description: Internal server error


  /api/userprofile/primaryemail{primaryemail}:
    get:
      tags:
        - User Profile Controller
      summary: Get user profile by primary email
      parameters:
        - name: primaryemail
          in: path
          required: true
          schema:
            type: string
            format: email
          description: Primary email address
      responses:
        '200':
          description: Profile found
        '404':
          description: Profile not found
        '500':
          description: Internal server error

  
#swagger definition for the Publication Controller
  /api/publications:  
    post:             #Create new publication 
      tags:
        - Publications Controller
      summary: Create a new publication for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                title:
                  type: string
                journal:
                  type: string
                link:
                  type: string
                  format: uri
                date_published:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Publication created successfully
        '500':
          description: Internal server error

  /api/publications/userid{userId}:
    get:                           #Get the publications for a user
      tags:
        - Publications Controller
      summary: Get publication by userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: User ID
      responses:
        '200':
          description: Publications found
        '404':
          description: Publications not found
        '500':
          description: Internal server error
    