version: "3"

services:
  give-it-a-good-name:
    image: zdy120939259/give-it-a-good-name:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - DATABASE
  postgres:
    image: "postgres"
    env_file:
      - ./.env
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: POSTGRES_DATA
        target: /data/postgresdb
    networks:
      - DATABASE
  nginx:
    restart: always
    image: nginx
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/cert.crt:/etc/nginx/conf.d/cert.crt
      - ./nginx/pk.key:/etc/nginx/conf.d/pk.key
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - give-it-a-good-name
      - postgres
    networks:
      - DATABASE
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - give-it-a-good-name
      - postgres
      - nginx
    networks:
      - DATABASE
networks:
  DATABASE:
    name: DATABASE
volumes:
  POSTGRES_DATA:
    name: POSTGRES_DATA