services:
  give-it-a-good-name:
    image: zdy120939259/give-it-a-good-name:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - DATABASE
  postgres:
    image: "postgres"
    env_file:
      - ./.env
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - type: volume
        source: POSTGRES_DATA
        target: /data/postgresdb
    networks:
      - DATABASE
networks:
  DATABASE:
    name: DATABASE
volumes:
  POSTGRES_DATA:
    name: POSTGRES_DATA
