version: "3"

services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      
    volumes:
    - type: volume
      source: POSTGRES_DATA
      target: /data/postgresdb
    networks:
      - DATABASE
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}  
    depends_on:
      - postgres
    ports:
      - "8888:80"
    networks:
      - DATABASE

networks:
  DATABASE:
    name: DATABASE
volumes:
  POSTGRES_DATA:
    name: POSTGRES_DATA