openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test API for user entity.
paths:
  /test-connection:
    get:
      summary: Tests the database connection to a Postgresql instance running on Aiven
      responses:
        '204':
          description: Connection successful. 
        '500':
          description: Error connecting to the database.
  /users:
    get:
      summary: Returns a list of users
      responses:
        '200':
          description: A JSON array of user objects
        '404':
          description: No records found
        '500':
          description: Internal server error
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                institution:
                  type: string
                email:
                  type: string
                  format: email
              required:
                - name
                - institution
                - email
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Internal Server error


